### Create Order
POST http://localhost:15672/api/exchanges/%2F/order.created/publish
Authorization: Basic user bitnami
Content-Type: application/json

{
  "properties": {
    "delivery_mode": 2
  },
  "routing_key": "",
  "payload": "{}",
  "payload_encoding": "string"
}

### Get Failed Orders
http://localhost:8080/orders/failed

