spring:
  application:
    name: item-order-service
  rabbitmq:
    username: user
    password: bitnami
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        orderCreated: # [SubscribableChannel]
          destination: order.created
          group: order-service
        orderBilled: # [SubscribableChannel]
          destination: order.billed
          group: order-service
        orderShipped: # [SubscribableChannel]
          destination: order.shipped
          group: order-service
        orderFailed: # [SubscribableChannel]
          destination: order.failed
          group: order-service
        failed: # [MessageChannel]
          destination: order.failed
CatalogService:
  ribbon:
    listOfServers: http://localhost:8000,http://localhost:8001
