spring:
  application:
    name: item-order-service
  rabbitmq:
    username: user
    password: bitnami
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        orders: # [SubscribableChannel]
          destination: orders
          group: examples
CatalogService:
  ribbon:
    listOfServers: http://localhost:8000,http://localhost:8001
