spring:
  application:
    name: item-order-service
  rabbitmq:
    username: user
    password: bitnami
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        orders: # [SubscribableChannel]
          destination: osEvents
          group: order-service
        payments: # [SubscribableChannel]
          destination: osEvents
          group: payment-service
        failures: # [MessageChannel]
          destination: osFailedEvents
          group: order-service
CatalogService:
  ribbon:
    listOfServers: http://localhost:8000,http://localhost:8001
